steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '.'
    id: 'Build'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
    id: 'Push'

  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--quiet'
    id: 'Deploy'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_ID}/${_SERVICE_NAME}:${SHORT_SHA}'

substitutions:
  _REGION: 'us-south1'
  _SERVICE_NAME: 'gbc-api-service'
  _REPO_ID: 'gbc-api-repo'

options:
  logging: CLOUD_LOGGING_ONLY